'use strict';

const LLVM_OPS = [
  'llvm.add',
  'llvm.addrspacecast',
  'llvm.alloca',
  'llvm.and',
  'llvm.ashr',
  'llvm.atomicrmw',
  'llvm.bitcast',
  'llvm.blockaddress',
  'llvm.blocktag',
  'llvm.br',
  'llvm.call',
  'llvm.call_intrinsic',
  'llvm.cmpxchg',
  'llvm.comdat',
  'llvm.comdat_selector',
  'llvm.cond_br',
  'llvm.dso_local_equivalent',
  'llvm.extractelement',
  'llvm.extractvalue',
  'llvm.fadd',
  'llvm.fcmp',
  'llvm.fdiv',
  'llvm.fence',
  'llvm.fmul',
  'llvm.fneg',
  'llvm.fpext',
  'llvm.fptosi',
  'llvm.fptoui',
  'llvm.fptrunc',
  'llvm.freeze',
  'llvm.frem',
  'llvm.fsub',
  'llvm.func',
  'llvm.getelementptr',
  'llvm.icmp',
  'llvm.indirectbr',
  'llvm.inline_asm',
  'llvm.insertelement',
  'llvm.insertvalue',
  'llvm.inttoptr',
  'llvm.invoke',
  'llvm.landingpad',
  'llvm.linker_options',
  'llvm.load',
  'llvm.lshr',
  'llvm.mlir.addressof',
  'llvm.mlir.alias',
  'llvm.mlir.constant',
  'llvm.mlir.global',
  'llvm.mlir.global_ctors',
  'llvm.mlir.global_dtors',
  'llvm.mlir.ifunc',
  'llvm.mlir.none',
  'llvm.mlir.poison',
  'llvm.mlir.undef',
  'llvm.mlir.zero',
  'llvm.module.flags',
  'llvm.module_flags',
  'llvm.mul',
  'llvm.or',
  'llvm.ptrtoint',
  'llvm.resume',
  'llvm.return',
  'llvm.sdiv',
  'llvm.select',
  'llvm.sext',
  'llvm.shl',
  'llvm.shufflevector',
  'llvm.sitofp',
  'llvm.srem',
  'llvm.store',
  'llvm.sub',
  'llvm.switch',
  'llvm.trunc',
  'llvm.udiv',
  'llvm.uitofp',
  'llvm.unreachable',
  'llvm.urem',
  'llvm.va_arg',
  'llvm.xor',
  'llvm.zext'
];

const LLVM_GENERIC_OPS = LLVM_OPS.filter(op => op !== 'llvm.func' && op !== 'llvm.return');

module.exports = {
  llvm_dialect: $ => prec.right(choice(
    seq('llvm.func', $._op_func),

    seq('llvm.return',
      field('attributes', optional($.attribute)),
      field('results', optional($._value_use_type_list))),

    seq(choice(...LLVM_GENERIC_OPS), optional($._llvm_generic_op_format))
  )),

  _llvm_generic_op_format: $ => repeat1(choice(
    $.value_use,
    $.symbol_ref_id,
    $.caret_id,
    $.integer_literal,
    $.float_literal,
    $.string_literal,
    $.type,
    $.attribute,
    $.region,
    $._value_use_list_parens,
    $._dense_idx_list,
    $.llvm_keyword,
    ',',
    ':',
    '=',
    '->',
    '#'
  )),

  llvm_keyword: $ => token(prec(-1, /[A-Za-z_][A-Za-z0-9_$-]*/))
}
