# Dedicated configuration file for Zed Editor
name = "MLIR"
grammar = "mlir"
path_suffixes = ["mlir"]
line_comments = ["//"]
autoclose_before = " \n\r\t};)>]"

[brackets]
paired = [
  { start = "{", end = "}" },
  { start = "[", end = "]" },
  { start = "(", end = ")" },
  { start = "<", end = ">" },
  { start = "\"", end = "\"" }
]
