name: Publish npm package

on:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  npm:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@216133f5cb4469b112c5e83415869e58b25c353a
    with:
      package-name: "@felixtensor/tree-sitter-mlir"
      node-version: "22"
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
